apiVersion: v1
kind: Service
metadata:
  name: poc-otel-web-svc
  namespace: development-arj
spec:
  selector:
    app: poc-otel-web
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: poc-otel-web
  namespace: development-arj
  labels:
    app: poc-otel-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-otel-web
  template:
    metadata:
      labels:
        app: poc-otel-web
    spec:
      imagePullSecrets:
        - name: secreto-docker-jfrog
      containers:
        - name: poc-otel-web
          image: imageAndVersion
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:8080"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: poc-otel-web
  namespace: development-arj
spec:
  host: poc-otel-web.apps.ocpmovistar001.interactivos.int
  to:
    kind: Service
    name: poc-otel-web-svc
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
